// <auto-generated />
using CSN.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSN.Migrations
{
    [DbContext(typeof(dbCSNChatContext))]
    [Migration("20241203102934_UpdateDbSchema")]
    partial class UpdateDbSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CSN.Models.tbMsg", b =>
                {
                    b.Property<int>("IdMsg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMsg"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tbUserUserId")
                        .HasColumnType("int");

                    b.HasKey("IdMsg");

                    b.HasIndex("RoomId");

                    b.HasIndex("tbUserUserId");

                    b.ToTable("tbMsg");
                });

            modelBuilder.Entity("CSN.Models.tbRoom", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<string>("RoomName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tbUserUserId")
                        .HasColumnType("int");

                    b.HasKey("RoomId");

                    b.HasIndex("tbUserUserId");

                    b.ToTable("tbRoom");
                });

            modelBuilder.Entity("CSN.Models.tbUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("PassWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("tbUser");
                });

            modelBuilder.Entity("CSN.Models.tbMsg", b =>
                {
                    b.HasOne("CSN.Models.tbRoom", "Room")
                        .WithMany("Messages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSN.Models.tbUser", null)
                        .WithMany("Messages")
                        .HasForeignKey("tbUserUserId");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CSN.Models.tbRoom", b =>
                {
                    b.HasOne("CSN.Models.tbUser", null)
                        .WithMany("Rooms")
                        .HasForeignKey("tbUserUserId");
                });

            modelBuilder.Entity("CSN.Models.tbRoom", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("CSN.Models.tbUser", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
